#include "shaderlib/cshader.h"
class debug_shadow_ortho_ps30_Static_Index
{
public:
	debug_shadow_ortho_ps30_Static_Index( )
	{
	}
	int GetIndex()
	{
		// Asserts to make sure that we aren't using any skipped combinations.
		// Asserts to make sure that we are setting all of the combination vars.
#ifdef _DEBUG
#endif // _DEBUG
		return 0;
	}
};
#define shaderStaticTest_debug_shadow_ortho_ps30 0
class debug_shadow_ortho_ps30_Dynamic_Index
{
public:
	debug_shadow_ortho_ps30_Dynamic_Index()
	{
	}
	int GetIndex()
	{
		// Asserts to make sure that we aren't using any skipped combinations.
		// Asserts to make sure that we are setting all of the combination vars.
#ifdef _DEBUG
#endif // _DEBUG
		return 0;
	}
};
#define shaderDynamicTest_debug_shadow_ortho_ps30 0
